services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001"
    ports:
      - "10000:10000"
      - "10001:10001"
    networks:
      - yetanotherecommerce_net

  database:
    image: postgres:16.11-alpine
    container_name: database
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - yetanotherecommerce_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: yetanotherecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: servicebus-emulator
    ports:
      - 5672:5672
    volumes:
      - ${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json:Z
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - mssql
    networks:
      sb-emulator:
        aliases:
          - sb-emulator

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    networks:
      sb-emulator:
        aliases:
          - mssql
  
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.Dev
    container_name: backend-dev
    ports:
      - 5001:5001
    networks:
      - yetanotherecommerce_net
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.Dev
    container_name: frontend-dev
    ports:
      - 5173:5173
    volumes:
      - ./apps/frontend:/usr/src/app:Z
      - type: volume
        target: /usr/src/app/node_modules
    environment:
      VITE_API_BASE_URL: "http://localhost:5001"
    networks:
      - yetanotherecommerce_net

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./mailpit:/data:Z
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pgdata:

networks:
  yetanotherecommerce_net:
    driver: bridge
  sb-emulator:
