@moduleUrl = http://localhost:5000/users-module
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhZTA5MC03ZDk1LTc4YmUtOWFlYS0zNjUxNDBmOGU2ODMiLCJ1bmlxdWVfbmFtZSI6IjAxOWFlMDkwLTdkOTUtNzhiZS05YWVhLTM2NTE0MGY4ZTY4MyIsImp0aSI6ImY0ZDAxZGQwLTZkYzEtNDRhZi05ZDYzLWIwMTM5MmUzZmY3MSIsImlhdCI6IjE3NjQ3MDYyNDEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJjdXN0b21lciIsIm5iZiI6MTc2NDcwNjI0MSwiZXhwIjoyMDgwMjQwODQxLCJpc3MiOiJZZXRBbm90aGVyRUNvbW1lcmNlIn0.NEYbjHXdNjDAY5J26KYGLyh9zcwTnO8qWt-bzwoKjAo

### Complete registration
POST {{moduleUrl}}/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "firstName": "Test",
    "lastName": "Test",
    "street": "Test 123",
    "city": "Test",
    "zipCode": "123-45",
    "country": "Test"
}