@moduleUrl = http://localhost:5000/identity-module
@email = test@yetanotherecommerce.com
@password = Super$ecret123

### Sign-up
POST {{moduleUrl}}/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Sign-in
# @name signIn
POST {{moduleUrl}}/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### 
@auth_token = {{signIn.response.body.$.accessToken}}

### Change password
POST {{moduleUrl}}/account/change-password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "currentPassword": "{{password}}",
    "newPassword": "newSuper$ecret123"
}