trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  basePath: 'apps/backend'
  solution: '$(basePath)/YetAnotherECommerce.sln'
  unitTestProjects: '$(basePath)/tests/**/*.UnitTests.csproj'
  bootstrapperProject: '$(basePath)/src/Bootstrapper/YetAnotherECommerce.Bootstrapper/YetAnotherECommerce.Bootstrapper.csproj'

steps:
- task: UseDotNet@2
  name: 'InstallDotNetSdk'
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

- task: DotNetCoreCLI@2
  name: 'RestoreSolution'
  displayName: 'Restore solution'
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  name: 'BuildSolution'
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  name: 'RunUnitTests'
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: '$(unitTestProjects)'
    arguments: '--configuration $(buildConfiguration) --no-build --no-restore'

- task: DotNetCoreCLI@2
  name: 'PublishProject'
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(bootstrapperProject)'
    arguments: '--configuration $(buildConfiguration) --no-build --no-restore --output $(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  name: 'PublishPipleineArtifact'
  displayName: 'Publish pipeline artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'yetanotherecommerce-backend'