trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'apps/frontend/**'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: frontend

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '20.x'

          - script: npm ci
            displayName: 'Install dependencies'
            workingDirectory: apps/frontend

          - script: npm run build
            displayName: 'Build app'
            workingDirectory: apps/frontend

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'apps/frontend/dist'
              artifactName: 'webapp'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: webapp

          - task: AzureStaticWebApp@0
            displayName: 'Deploy to Azure Static Web Apps'
            inputs:
              app_location: '$(Pipeline.Workspace)/webapp'
              output_location: ''
              skip_app_build: true
              skip_api_build: true
              azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)