trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.6'

stages:
  - stage: Validate
    jobs:
    - job: validate
      steps:
      - bash: |
          curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          unzip terraform_${TF_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform version
        displayName: 'Install Terraform'

      - bash: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate
        workingDirectory: '$(Build.SourcesDirectory)/infrastructure'
        displayName: 'Terraform Validate'
