trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'infrastructure/**'

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: arm
- group: arm-tfstate-platform

- name: TF_VERSION
  value: '1.14.5'
- name:  TF_DIR
  value: '$(Build.SourcesDirectory)/infrastructure'
- name: TF_HAS_CHANGES
  value: false

stages:
  - stage: Validate
    jobs:
    - job: validate
      steps:
      - template: templates/terraform/terraform-install.yml

      - bash: |
          terraform init -backend=false -input=false -no-color
          terraform fmt -check -no-color
          terraform validate -no-color
        workingDirectory: $(TF_DIR)
        displayName: 'Terraform Validate'

  - stage: Plan
    dependsOn: Validate
    condition: succeeded()
    jobs:
    - job: plan
      steps:
      - template: templates/terraform/terraform-install.yml

      - template: templates/terraform/terraform-init.yml
        parameters:
          tfDir: $(TF_DIR)

      - bash: |
          terraform plan -out=tfplan -detailed-exitcode -input=false -no-color
          PLAN_EXIT_CODE=$?

          if [ $PLAN_EXIT_CODE -eq 2 ]; then
            echo "##vso[task.setvariable variable=TF_HAS_CHANGES;isOutput=true]true"
          elif [ $PLAN_EXIT_CODE -eq 1 ]; then
            exit 1
          fi
        name: terraformPlan
        displayName: 'Terraform Plan'
        workingDirectory: $(TF_DIR)
        env:
          TF_VAR_subscription_id: $(arm_subscription_id)
          TF_VAR_sql_administrator_login: $(sql_administrator_login)
          TF_VAR_sql_administrator_password: $(sql_administrator_password)
      
      - publish: $(TF_DIR)/tfplan
        artifact: tfplan

  - stage: Apply
    dependsOn: Plan
    condition: and(succeeded(), eq(stageDependencies.Plan.outputs['plan.terraformPlan.TF_HAS_CHANGES'], 'true'))
    jobs:
    - job: apply
      steps:
      - download: current
        artifact: tfplan

      - template: templates/terraform/terraform-install.yml

      - template: templates/terraform/terraform-init.yml
        parameters:
          tfDir: $(TF_DIR)

      - bash: terraform apply -input=false -no-color $(Pipeline.Workspace)/tfplan/tfplan
        workingDirectory: $(TF_DIR)
        displayName: 'Terraform Apply'