@moduleUrl = http://localhost:5000/products-module

### Get all products
GET {{moduleUrl}}/products

### Add product
POST {{moduleUrl}}/products
Content-Type: application/json

{
    "name": "Apple iPhone 13 Pro",
    "price": 3999.99,
    "quantity": 100
}

###
@productId =

### Add product to cart
POST {{moduleUrl}}/products/add-to-cart
Content-Type: application/json

{
    "productId": "{{productId}}",
    "quantity": 10
}

### Update product quantity
POST {{moduleUrl}}/products/update-quantity
Content-Type: application/json

{
    "productId": "{{productId}}",
    "quantity": 10
}


###
DELETE {{moduleUrl}}/products/{{productId}}