@moduleUrl = http://localhost:5000/orders-module
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhZTA5MC03ZDk1LTc4YmUtOWFlYS0zNjUxNDBmOGU2ODMiLCJ1bmlxdWVfbmFtZSI6IjAxOWFlMDkwLTdkOTUtNzhiZS05YWVhLTM2NTE0MGY4ZTY4MyIsImp0aSI6ImY0ZDAxZGQwLTZkYzEtNDRhZi05ZDYzLWIwMTM5MmUzZmY3MSIsImlhdCI6IjE3NjQ3MDYyNDEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJjdXN0b21lciIsIm5iZiI6MTc2NDcwNjI0MSwiZXhwIjoyMDgwMjQwODQxLCJpc3MiOiJZZXRBbm90aGVyRUNvbW1lcmNlIn0.NEYbjHXdNjDAY5J26KYGLyh9zcwTnO8qWt-bzwoKjAo
@orderId = 

### Browse
GET {{moduleUrl}}/orders
Authorization: Bearer {{accessToken}}

### Browse my orders
GET {{moduleUrl}}/orders/my-orders
Authorization: Bearer {{accessToken}}

### Get order details
GET {{moduleUrl}}/orders/my-orders/{{orderId}}
Authorization: Bearer {{accessToken}}

### Cancel order
POST {{moduleUrl}}/orders/my-orders/{{orderId}}/cancel
Authorization: Bearer {{accessToken}}

### Complete order
POST {{moduleUrl}}/orders/{{orderId}}/complete
Authorization: Bearer {{accessToken}}

### Revoke order
POST {{moduleUrl}}/orders/{{orderId}}/revoke
Authorization: Bearer {{accessToken}}