@moduleUrl = http://localhost:5000/identity-module
@email = test@yetanotherecommerce.com
@password = super$ecret
@role = admin

### Sign-up
POST {{moduleUrl}}/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "role": "{{role}}"
}

### Sign-in
POST {{moduleUrl}}/sign-in
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### 
@jwt =

### Change email
POST {{moduleUrl}}/account/change-email
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "email": "newemailaddress@yetanotherecommerce.com"
}